version: "3"

services:

  nextcloud:
    build: docker/nextcloud
    ports:
      - 9999:80
    links:
      - mysql
    volumes:
      - ./var/nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.144.23,volafacile.javanile.org
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=mysql

  collabora:
    build: docker/collabora
    ports:
      - 9980:9980
    environment:
      - username=collabora
      - password=collabora
      #- extra_params=--o:ssl.enable=false

  mysql:
    build: docker/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud

  adminer:
    image: adminer
    ports:
      - 9998:8080


