version: "3"

services:

  nginx:
    build: docker/nginx
    ports:
      - 9990:80
    links:
      - nextcloud
      - collabora
    restart: always

  nextcloud:
    build: docker/nextcloud
    ports:
      - 9999:80
    links:
      - mysql
    volumes:
      - ./var/nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.144.23 volafacile.javanile.org
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=mysql
    restart: always

  collabora:
    build: docker/collabora
    ports:
      - 9980:9980
    environment:
      - username=collabora
      - password=collabora
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: always

  guacamole:
    image: guacamole/guacamole:1.5.1
    ports:
      - 9970:8080
    environment:
      - GUACD_HOSTNAME=guacd
      - EXTENSIONS=auth-totp
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    links:
      - guacd
      - mysql
    restart: always

  guacd:
    image: guacamole/guacd:1.5.1
    ports:
      - 4822:4822
    restart: always

  mysql:
    build: docker/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
    restart: always

  adminer:
    image: adminer
    ports:
      - 9998:8080
    restart: always

  backup:
    image: javanile/backup
    command:
      - '0 0 * * * /usr/local/bin/backup.sh daily'
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=nextcloud
      - DB_NAME=nextcloud
      - FTP_PROTO=ftp
      - FTP_HOST=192.168.144.50
      - FTP_USER=backup
      - FTP_PASS=Backup1234!
      - REMOTE_PATH=/Machines/Volafacile
    volumes:
      - ./var/mysql:/data/mysql
      - ./var/nextcloud:/data/nextcloud
    links:
      - mysql
    restart: always
